### ISSUE TITLE
ERROR org.mockserver.mock.HttpStateHandler - Exception while returning writing

### ISSUE THREAD

**Issue by fauberso** [riot-framework/sbt-riotctl#1]
On newer versions of Raspbian, the following happens when deploying:

```
13:18:56.758 [nioEventLoopGroup-4-39] ERROR org.mockserver.mock.HttpStateHandler - Exception while returning writing HttpObjectAggregator$AggregatedFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(freed, components=462))
HTTP/1.1 200 OK
Date: Sat, 28 Sep 2019 11:18:55 GMT
Server: Apache/2.4.39 (Fedora)
Last-Modified: Thu, 01 Aug 2019 09:33:48 GMT
ETag: "b8d550-58f0af0537700"
Accept-Ranges: bytes
Content-Length: 12113232
Keep-Alive: timeout=10, max=500
Content-Type: application/x-debian-package
connection: keep-alive
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[?:1.8.0_151]
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51) ~[?:1.8.0_151]
	at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[?:1.8.0_151]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504) ~[?:1.8.0_151]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:420) ~[?:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:939) ~[?:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:367) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:676) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534) ~[?:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[?:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[?:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
java.io.IOException: Operation returned exit status 100
	at riot.riotctl.internal.SSHClient.exec(SSHClient.java:141)
	at riot.riotctl.RiotCtlTool.ensurePackages(RiotCtlTool.java:77)
	at riot.riotctl.sbt.RiotCtl$.$anonfun$runTask$1(RiotCtl.scala:96)
	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:67)
	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
	at sbt.Execute.work(Execute.scala:278)
	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[info] W: http://archive.raspberrypi.org/debian/pool/main/m/mesa/libglapi-mesa_19.2.0~rc1-1~bpo10+1~rpt2_armhf.deb: Automatically disabled Acquire::http::Pipeline-Depth due to incorrect response from server/proxy. (man 5 apt.conf)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[info] W: http://debian.anexia.at/raspbian/raspbian/pool/main/libx/libxrender/libxrender1_0.9.10-1_armhf.deb: Automatically disabled Acquire::http::Pipeline-Depth due to incorrect response from server/proxy. (man 5 apt.conf)
[info] W: http://mirror1.hs-esslingen.de/pub/Mirrors/archive.raspbian.org/raspbian/pool/main/p/pango1.0/libpangocairo-1.0-0_1.42.4-7~deb10u1_armhf.deb: Automatically disabled Acquire::http::Pipeline-Depth due to incorrect response from server/proxy. (man 5 apt.conf)
[info] E: Failed to fetch http://debian.anexia.at/raspbian/raspbian/pool/main/libx/libxrender/libxrender1_0.9.10-1_armhf.deb  File has unexpected size (50928 != 99264). Mirror sync in progress? [IP: ::1 8080]
[info]    Hashes of expected file:
[info]     - SHA256:d6d35c9e57153832d88a521eb22acb19639e80003de7f3d9c834162fe8e4b5da
[info]     - SHA1:03e32325f04b8fc65f0e25f58506c436aaea4256 [weak]
[info]     - MD5Sum:d86dc13c48cd9adaa318bd30c49f3102 [weak]
[info]     - Filesize:99264 [weak]
[info] E: Failed to fetch http://debian.anexia.at/raspbian/raspbian/pool/main/libd/libdatrie/libdatrie1_0.2.12-2_armhf.deb  File has unexpected size (35900 != 404152). Mirror sync in progress? [IP: ::1 8080]
[info]    Hashes of expected file:
[info]     - SHA256:f2d17a9588f37d149e2777bdeb6acbc8bad203b814c8983b34ddee24ce316421
[info]     - SHA1:68ecdbb49989bebee1f7c7ce3c22471c5f0c1eda [weak]
[info]     - MD5Sum:6f7a7174d3ca147c6d1b43c92b32280a [weak]
[info]     - Filesize:404152 [weak]
```

**Comment by fauberso** [comment]
The newer apt-get versions use pipelining, but the Proxy used in Riotctl doesn't handle it correctly. Calling apt-get with '-o Acquire::http::No-Cache=true' and '-o Acquire::http::Pipeline-Depth=0' disable pipelining.

Fixed in sbt-riotctl 0.5 and riotctl 0.5
